version: "3.8"

services:
  redis:
    image: redis:7
    container_name: modelx-redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    command: redis-server --appendonly yes

  postgres:
    image: postgres:15
    container_name: modelx-postgres
    environment:
      POSTGRES_DB: modelx
      POSTGRES_USER: modelxuser
      POSTGRES_PASSWORD: modelxpass
    ports:
      - "5432:5432"
    volumes:
      - pg-data:/var/lib/postgresql/data
      - ./init_db.sql:/docker-entrypoint-initdb.d/init_db.sql   # MOUNT SQL FILE

volumes:
  redis-data:
  pg-data:
